# Generated by Django 6.0 on 2025-12-16 07:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('biografia', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('Crecimiento', 'Crecimiento'), ('Matrimonio', 'Matrimonio'), ('Cosmovisión', 'Cosmovisión'), ('Apologética', 'Apologética'), ('Crianza', 'Crianza'), ('Ministerial', 'Ministerial'), ('Estudio Bíblico', 'Estudio Bíblico'), ('Niños', 'Niños'), ('Teología', 'Teología'), ('Devocional', 'Devocional'), ('Historia', 'Historia'), ('Filosofía y Ciencia', 'Filosofía y Ciencia'), ('Consejería', 'Consejería'), ('Discipulado', 'Discipulado'), ('Novelas', 'Novelas'), ('Escatología', 'Escatología'), ('Contemporáneos', 'Contemporáneos'), ('Varios', 'Varios')], max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('isbn', models.CharField(blank=True, max_length=50, null=True)),
                ('stock', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('disponible', models.BooleanField(default=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='libros', to='biblioteca.autor')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='libros', to='biblioteca.categoria')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
                'ordering': ['-fecha_ingreso'],
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateTimeField(auto_now_add=True)),
                ('fecha_devolucion_esperada', models.DateField()),
                ('fecha_devolucion_real', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='biblioteca.libro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Préstamo',
                'verbose_name_plural': 'Préstamos',
                'ordering': ['-fecha_prestamo'],
            },
        ),
        migrations.AddIndex(
            model_name='libro',
            index=models.Index(fields=['titulo'], name='biblioteca__titulo_c16bf1_idx'),
        ),
        migrations.AddIndex(
            model_name='libro',
            index=models.Index(fields=['categoria'], name='biblioteca__categor_bdb99c_idx'),
        ),
        migrations.AddIndex(
            model_name='libro',
            index=models.Index(fields=['autor'], name='biblioteca__autor_i_e0b329_idx'),
        ),
    ]
